function_php = [{'name':'deprecated','function':'call_user_method(','replace':'call_user_func()'},
				{'name':'deprecated','function':'call_user_method_array(','replace':'call_user_func_array()'},
				{'name':'deprecated','function':'define_syslog_variables(','replace':''},
				{'name':'deprecated','function':'dl(','replace':''},
				{'name':'deprecated','function':'ereg(','replace':'preg_match()'},
				{'name':'deprecated','function':'ereg_replace(','replace':'preg_replace()'},
				{'name':'deprecated','function':'eregi(','replace':'preg_match()'},
				{'name':'deprecated','function':'eregi_replace(','replace':'preg_replace()'},
				{'name':'deprecated','function':'set_magic_quotes_runtime(','replace':'magic_quotes_runtime()'},
				{'name':'deprecated','function':'session_register(','replace':'$_SESSION'},
				{'name':'deprecated','function':'session_unregister(','replace':'$_SESSION'},
				{'name':'deprecated','function':'session_is_registered(', 'replace':'$_SESSION'},
				{'name':'deprecated','function':'set_socket_blocking(','replace':'stream_set_blocking()'},
				{'name':'deprecated','function':'split(','replace':'preg_split()'},
				{'name':'deprecated','function':'spliti(','replace':'preg_split()'},
				{'name':'deprecated','function':'sql_regcase(','replace':''},
				{'name':'deprecated','function':'mysql_db_query(','replace':''},
				{'name':'deprecated','function':'mysql_query(','replace':'PDO::query()'},
				{'name':'deprecated','function':'mysql_escape_string(','replace':''},
				{'name':'deprecated','function':'mysql_real_escape_string(','replace':'PDO::quote()'},
				{'name':'rowCount','function':'->rowCount(', 'replace':''},
				{'name':'include','function':'include($_GET[', 'replace':''},
				{'name':'RCE', 'function':'eval(','replace':''},
				{'name':'RCE', 'function':'shell_exec', 'replace':''}
				]