function_php = [{'deprecated':'call_user_method(','replace':'call_user_func()'},
				{'deprecated':'call_user_method_array(','replace':'call_user_func_array()'},
				{'deprecated':'define_syslog_variables(','replace':''},
				{'deprecated':'dl(','replace':''},
				{'deprecated':'ereg(','replace':'preg_match()'},
				{'deprecated':'ereg_replace(','replace':'preg_replace()'},
				{'deprecated':'eregi(','replace':'preg_match()'},
				{'deprecated':'eregi_replace(','replace':'preg_replace()'},
				{'deprecated':'set_magic_quotes_runtime(','replace':'magic_quotes_runtime()'},
				{'deprecated':'session_register(','replace':'$_SESSION'},
				{'deprecated':'session_unregister(','replace':'$_SESSION'},
				{'deprecated':'session_is_registered(', 'replace':'$_SESSION'},
				{'deprecated':'set_socket_blocking(','replace':'stream_set_blocking()'},
				{'deprecated':'split(','replace':'preg_split()'},
				{'deprecated':'spliti(','replace':'preg_split()'},
				{'deprecated':'sql_regcase(','replace':''},
				{'deprecated':'mysql_db_query(','replace':''},
				{'deprecated':'mysql_query(','replace':'PDO::query()'},
				{'deprecated':'mysql_escape_string(','replace':''},
				{'deprecated':'mysql_real_escape_string(','replace':'PDO::quote()'}
				]